# -*- coding: utf-8 -*-
"""In_Person_07302024_Exercise_bracketmatcher

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xd666lykld4NjTIqHjv6oVWJSMnP7eTO
"""

def bracket_matcher(characters):
  open_count = 0
  close_count = 0
  for c in characters:
    if c == "(":
      open_count += 1
    elif c == ")":
      close_count += 1
  if open_count == close_count:
    return True
  else:
    return False

s = "(a((kl(mns)t)uvwz))"
bracket_matcher(s)
